// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhrO1blVQNC_szZJ4Q2bZrKcsejtDSU5k',
    appId: '1:498664374723:web:ebeb22c38a2a53a01d3d76',
    messagingSenderId: '498664374723',
    projectId: 'esgi-tweet',
    authDomain: 'esgi-tweet.firebaseapp.com',
    storageBucket: 'esgi-tweet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZisQWscBA6jniUGa-3yXuv5Vl8YsQx5k',
    appId: '1:498664374723:android:f2379e433944f3961d3d76',
    messagingSenderId: '498664374723',
    projectId: 'esgi-tweet',
    storageBucket: 'esgi-tweet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4D-par_qy6jbZG4ls1DKDRcKtHgyA3ss',
    appId: '1:498664374723:ios:0ebb194826e5ad541d3d76',
    messagingSenderId: '498664374723',
    projectId: 'esgi-tweet',
    storageBucket: 'esgi-tweet.appspot.com',
    iosClientId: '498664374723-vbk57l1qbgptdao4ijaulqqmg86eu3r3.apps.googleusercontent.com',
    iosBundleId: 'com.moc.sms.esgiTweet',
  );
}
